import prisma from '../lib/prisma.js';

async function main() {
  const volunteer = await prisma.volunteer.createMany({
    data: [
      {
        firstName: 'Tony',
        lastName: 'Barnert',
        email: 't2t@sonic.net',
        phone: '',
        street: '',
        city: '',
        state: '',
        zip: '',
      },
      {
        firstName: 'Serena',
        lastName: 'Berman',
        email: 'berman.serena@gmail.com',
        phone: '',
        street: '',
        city: '',
        state: '',
        zip: '',
      },
      {
        firstName: 'Linda',
        lastName: 'Brown',
        email: 'teambrown@sbcglobal.net',
        phone: '',
        street: '',
        city: '',
        state: '',
        zip: '',
      },
      {
        firstName: 'Alan',
        lastName: 'Channing',
        email: 'ahc.1440@gmail.com',
        phone: '',
        street: '',
        city: '',
        state: '',
        zip: '',
      },
      {
        firstName: 'Ronda',
        lastName: 'Channing',
        email: 'ronda_channing@yahoo.com',
        phone: '3126368229',
        street: '',
        city: '',
        state: '',
        zip: '10023',
      },
      {
        firstName: 'Melodie',
        lastName: 'Cooper',
        email: 'melodierosecooper@yahoo.com',
        phone: '',
        street: '',
        city: '',
        state: '',
        zip: '',
      },
      {
        firstName: 'Allison',
        lastName: 'Costine',
        email: 'Alicost@gmail.com',
        phone: '',
        street: '',
        city: '',
        state: '',
        zip: '',
      },
      {
        firstName: 'Laura',
        lastName: 'Estersohn',
        email: 'lestersohn@gmail.com',
        phone: '',
        street: '',
        city: '',
        state: '',
        zip: '',
      },
      {
        firstName: 'Henry',
        lastName: 'Freedman',
        email: 'henryafreedman@gmail.com',
        phone: '',
        street: '',
        city: '',
        state: '',
        zip: '',
      },
      {
        firstName: 'Jeffrey',
        lastName: 'Gutman',
        email: 'gutmanbrustin@verizon.net',
        phone: '',
        street: '',
        city: '',
        state: '',
        zip: '',
      },
      {
        firstName: 'Wendy',
        lastName: 'Holtzman',
        email: 'wholtzman717@gmail.com',
        phone: '',
        street: '',
        city: '',
        state: '',
        zip: '',
      },
      {
        firstName: 'Elissa',
        lastName: 'Holzman',
        email: 'emholzman@yahoo.com',
        phone: '9179419170',
        street: '',
        city: '',
        state: '',
        zip: '10520',
      },
      {
        firstName: 'Katie',
        lastName: 'Knecht',
        email: 'ktkrnc@verizon.net',
        phone: '',
        street: '',
        city: '',
        state: '',
        zip: '',
      },
      {
        firstName: 'Carolyn',
        lastName: 'Long',
        email: 'cglong630@gmail.com',
        phone: '',
        street: '',
        city: '',
        state: '',
        zip: '',
      },
      {
        firstName: 'Julie',
        lastName: 'Minter',
        email: 'minterjulie4@gmail.com',
        phone: '',
        street: '',
        city: '',
        state: '',
        zip: '',
      },
      {
        firstName: 'Carol',
        lastName: 'Moore',
        email: 'carol_m_moore@yahoo.com',
        phone: '',
        street: '',
        city: '',
        state: '',
        zip: '',
      },
      {
        firstName: 'Beth',
        lastName: 'Moorsmith',
        email: 'bethmoorsmith@gmail.com',
        phone: '',
        street: '',
        city: '',
        state: '',
        zip: '',
      },
      {
        firstName: 'Morgana',
        lastName: 'Rae',
        email: 'morganarae@gmail.com',
        phone: '',
        street: '',
        city: '',
        state: '',
        zip: '',
      },
      {
        firstName: 'Thomas',
        lastName: 'Slone',
        email: 'thslone@gmail.com',
        phone: '5107153102',
        street: '',
        city: '',
        state: '',
        zip: '94611',
      },
      {
        firstName: 'Joyce',
        lastName: 'Thornhill',
        email: 'variegator@aol.com',
        phone: '',
        street: '',
        city: '',
        state: '',
        zip: '',
      },
      {
        firstName: 'Johannah',
        lastName: 'Townsend',
        email: 'thetownsendfamily@gmail.com',
        phone: '',
        street: '',
        city: '',
        state: '',
        zip: '',
      },
    ],
    skipDuplicates: true,
  });
  console.log(volunteer);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
