import { OneVolunteer } from '../components';

const Hit = ({
  hit,
  getId,
  id,
  deleteHandler,
  updateVolunteer,
  objectID,
  firstName,
  lastName,
  email,
  street,
  city,
  state,
  zip,
  phone,
  userId,
  events,
  campaignMgmt,
  canvassing,
  communityOrganizing,
  electedOfficialCurr,
  electedOfficialPast,
  p2pTextingMgmt,
  p2pTextingVol,
  phonebanking,
  pollWorker,
  postcardMgmt,
  postcardWriting,
  txtPhoneScriptEdit,
  txtPhoneScriptWrite,
  vanVoteBuildExp,
  voterReg,
  actor,
  artist,
  boardOfDirectors,
  dataScience,
  dbMgmt,
  editor,
  professor,
  trainer,
  fundraising,
  graphicDesign,
  hr,
  it,
  legal,
  linguist,
  msgComms,
  musician,
  newsletterCreateDesign,
  newsletterWrite,
  nonprofMgmt,
  pr,
  publicSpeak,
  recruitment,
  research,
  otherLanguage,
  socialMediaContentCreate,
  socialMediaMgmt,
  speechWriter,
  strategicPlanning,
  videoEditCreate,
  volMgmt,
  webDesign,
  webMgmt,
  anythingElse,
}) => {
  return (
    <>
      <OneVolunteer
        firstName={hit.firstName}
        lastName={hit.lastName}
        email={hit.email}
        street={hit.street}
        city={hit.city}
        state={hit.state}
        zip={hit.zip}
        phone={hit.phone}
        userId={hit.userId}
        events={hit.events}
        campaignMgmt={hit.campaignMgmt}
        getId={getId}
        id={hit.id}
        deleteHandler={deleteHandler}
        updateVolunteer={updateVolunteer}
        objectID={hit.objectID}
        canvassing={hit.canvassing}
        communityOrganizing={hit.communityOrganizing}
        electedOfficialCurr={hit.electedOfficialCurr}
        electedOfficialPast={hit.electedOfficialPast}
        p2pTextingMgmt={hit.p2pTextingMgmt}
        p2pTextingVol={hit.p2pTextingVol}
        phonebanking={hit.phonebanking}
        pollWorker={hit.pollWorker}
        postcardMgmt={hit.postcardMgmt}
        postcardWriting={hit.postcardWriting}
        txtPhoneScriptEdit={hit.txtPhoneScriptEdit}
        txtPhoneScriptWrite={hit.txtPhoneScriptWrite}
        vanVoteBuildExp={hit.vanVoteBuildExp}
        voterReg={hit.voterReg}
        actor={hit.actor}
        artist={hit.artist}
        boardOfDirectors={hit.boardOfDirectors}
        dataScience={hit.dataScience}
        dbMgmt={hit.dbMgmt}
        editor={hit.editor}
        professor={hit.professor}
        trainer={hit.trainer}
        fundraising={hit.fundraising}
        graphicDesign={hit.graphicDesign}
        hr={hit.hr}
        it={hit.it}
        legal={hit.legal}
        linguist={hit.linguist}
        msgComms={hit.msgComms}
        musician={hit.musician}
        newsletterCreateDesign={hit.newsletterCreateDesign}
        newsletterWrite={hit.newsletterWrite}
        nonprofMgmt={hit.nonprofMgmt}
        pr={hit.pr}
        publicSpeak={hit.publicSpeak}
        recruitment={hit.recruitment}
        research={hit.research}
        otherLanguage={hit.otherLanguage}
        socialMediaContentCreate={hit.socialMediaContentCreate}
        socialMediaMgmt={hit.socialMediaMgmt}
        speechWriter={hit.speechWriter}
        strategicPlanning={hit.strategicPlanning}
        videoEditCreate={hit.videoEditCreate}
        volMgmt={hit.volMgmt}
        webDesign={hit.webDesign}
        webMgmt={hit.webMmgmt}
        anythingElse={hit.anythingElse}
      />
    </>
  );
};

export default Hit
